### ISSUE TITLE
Usando state en React para cambiar estilo

### ISSUE THREAD

**Issue by santiagotrini** [Maxy92/brawlbase#2]
Fijense esto:

```js
import { useState } from 'react';

const App = () => {

  const [mouseOver, setMouseOver] = useState(false);
  const [style, setStyle] = useState({
    opacity: '100%'
  });
  const changeBG = e => {
    console.log(e);
    if (e.type === 'mouseenter') {
      setStyle({
        opacity: '50%'
      });
    } else {
      setStyle({
        opacity: '100%'
      });
    }
  }

  return (
    <div
      style={style}
      className="cuadradito"
      onMouseEnter={changeBG}
      onMouseLeave={changeBG}
    >
    </div>
  );
}

export default App;

```

```css
.cuadradito {
  height: 400px;
  width: 400px;
  animation: colorRotate 6s linear 0s infinite;
}

@keyframes colorRotate {
  from {
    background: #6666ff;
  }
  10% {
    background: #0099ff;
  }
  50% {
    background: #00ff00;
  }
  75% {
    background: #ff3399;
  }
  100% {
    background: #6666ff;
  }
}


```
